name: Deploy Frontend (Production)

on:
  push:
    branches:
      - production

  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. STRICT PRODUCTION BRANCH CHECK
      - name:  Branch Restriction Check
        if: github.ref != 'refs/heads/production'
        run: |
          echo " ERROR: Deployment is allowed ONLY from production branch."
          echo "Selected branch: ${{ github.ref }}"
          exit 1

      # 2. DEPLOY TO SERVER
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            sudo /usr/local/bin/bookqik_frontend_deploy.sh
